server:
  port: 8761

spring:
  application:
    name: EurekaServer
     
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
       
---

spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    
