spring:
  application:
    name: EurekaServer
     
server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
      waitTimeInMsWhenSyncEmpty: 0
       
---

spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    
